### ISSUE TITLE
issue: cursor seems to change to a fallback one when hovering over the app

### ISSUE THREAD

**Issue by amycatgirl** [flathub/chat.revolt.RevoltDesktop#24]
![image](https://github.com/user-attachments/assets/18f35829-c53d-477e-b1c0-62fdb2b90667)

Also the header font I'm using should be Inter Display, not the fallback "Sans" font, which seems to be used there.

The issue persists across reboots.

**Comment by RayJW** [comment]
Huh, that's weird. I recently merged #23 to exactly alleviate this issue on most common setups. I assume you're fully updated, and this issue is still happening? If yes, could you try whether this issue started occurring with the latest update, depending on how long you've been using the Flatpak?

As you can see [here](https://github.com/search?q=org%3Aflathub%20env%3DXCURSOR_PATH%3D%2Frun%2Fhost%2Fuser-share%2Ficons%3A%2Frun%2Fhost%2Fshare%2Ficons&type=code), this is how close to all well maintained Electron Flatpak packages handle mouse cursor themes. Do you have the same issue with any of those, say Discord, Signal, Spotify for example?

Could you give some more info like what DE are you running, how and where is your mouse cursor theme set, etc.?

**Comment by amycatgirl** [comment]
Just checked for updates and it looks like I didn't update.

I'll close the issue if needed.

Also I use Discord and I haven't had that issue.

I'm running Fedora Workstation 41, Gnome 47, and use Adwaita as my cursor and GTK 3+ theme

**Comment by amycatgirl** [comment]
Alright the issue seems to be fixed. Many thanks!

**Comment by RayJW** [comment]
Oh, alright that's good! Funny that no one reported this issue for years and the second I release a fix someone realises :D
